name = "CanEvolve"
uuid = "dd73d47d-4532-4b1f-8e59-6f7dc77678bc"
authors = ["Tom W Ouellette"]
version = "0.1.0"

[compat]
julia = "1.5.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
