name = "CanEvolve"
uuid = "28e55d1b-a762-458a-aac7-95dc06097867"
authors = ["Tom W Ouellette"]
version = "0.1.0"

[compat]
julia = "1.5.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
